heat_template_version: 2013-05-23

description: Test template to create one instance.

parameters:
  MyPotato: {default: '6:6666', type: comma_delimited_list}

resources:
  test1:
    type: One::Resource
    properties:
     MyPotato: {get_param: MyPotato}
